Fix error handler on IndexingService#indexOnStartup
If we don't register the handler in the subscriber, we get an additional
exception in the stack:
java.lang.Exception: Missing onFailure/onError handler in the subscriber